# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bloom.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x62loom.proto\x12\x02pb\"\x1d\n\rFilterRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\"(\n\nKeyRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0c\n\x04Keys\x18\x02 \x03(\t\"\r\n\x0bListRequest\"&\n\x08Response\x12\x1a\n\x06Status\x18\x01 \x01(\x0e\x32\n.pb.Status\"6\n\x0bHasResponse\x12\x1a\n\x06Status\x18\x01 \x01(\x0e\x32\n.pb.Status\x12\x0b\n\x03Has\x18\x02 \x03(\x08\"\x1d\n\x0cListResponse\x12\r\n\x05Names\x18\x01 \x03(\t\"+\n\x0cInfoResponse\x12\x1b\n\x07\x46ilters\x18\x01 \x03(\x0b\x32\n.pb.Filter\"y\n\x06\x46ilter\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x08\x43\x61pacity\x18\x02 \x01(\x03\x12\x0c\n\x04Hits\x18\x03 \x01(\x03\x12\x0e\n\x06Misses\x18\x04 \x01(\x03\x12\x0e\n\x06\x43hecks\x18\x05 \x01(\x03\x12\x13\n\x0bProbability\x18\x06 \x01(\x01\x12\x0c\n\x04Keys\x18\x07 \x01(\x03*\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\xc3\x02\n\x05\x42loom\x12\x31\n\x0c\x43reateFilter\x12\x11.pb.FilterRequest\x1a\x0c.pb.Response\"\x00\x12\x32\n\x0bListFilters\x12\x0f.pb.ListRequest\x1a\x10.pb.ListResponse\"\x00\x12+\n\x04Info\x12\x0f.pb.ListRequest\x1a\x10.pb.InfoResponse\"\x00\x12%\n\x03\x41\x64\x64\x12\x0e.pb.KeyRequest\x1a\x0c.pb.Response\"\x00\x12(\n\x03Has\x12\x0e.pb.KeyRequest\x1a\x0f.pb.HasResponse\"\x00\x12*\n\x05\x43lear\x12\x11.pb.FilterRequest\x1a\x0c.pb.Response\"\x00\x12)\n\x04\x44rop\x12\x11.pb.FilterRequest\x1a\x0c.pb.Response\"\x00\x42\x04Z\x02pbb\x06proto3')
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pb.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=402,
  serialized_end=436,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
SUCCESS = 0
FAILURE = 1



_FILTERREQUEST = _descriptor.Descriptor(
  name='FilterRequest',
  full_name='pb.FilterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='pb.FilterRequest.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=48,
)


_KEYREQUEST = _descriptor.Descriptor(
  name='KeyRequest',
  full_name='pb.KeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='pb.KeyRequest.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Keys', full_name='pb.KeyRequest.Keys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=90,
)


_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='pb.ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=105,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='pb.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='pb.Response.Status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=145,
)


_HASRESPONSE = _descriptor.Descriptor(
  name='HasResponse',
  full_name='pb.HasResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='pb.HasResponse.Status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Has', full_name='pb.HasResponse.Has', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=201,
)


_LISTRESPONSE = _descriptor.Descriptor(
  name='ListResponse',
  full_name='pb.ListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Names', full_name='pb.ListResponse.Names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=232,
)


_INFORESPONSE = _descriptor.Descriptor(
  name='InfoResponse',
  full_name='pb.InfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Filters', full_name='pb.InfoResponse.Filters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=277,
)


_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='pb.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='pb.Filter.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Capacity', full_name='pb.Filter.Capacity', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Hits', full_name='pb.Filter.Hits', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Misses', full_name='pb.Filter.Misses', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Checks', full_name='pb.Filter.Checks', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Probability', full_name='pb.Filter.Probability', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Keys', full_name='pb.Filter.Keys', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=400,
)

_RESPONSE.fields_by_name['Status'].enum_type = _STATUS
_HASRESPONSE.fields_by_name['Status'].enum_type = _STATUS
_INFORESPONSE.fields_by_name['Filters'].message_type = _FILTER
DESCRIPTOR.message_types_by_name['FilterRequest'] = _FILTERREQUEST
DESCRIPTOR.message_types_by_name['KeyRequest'] = _KEYREQUEST
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['HasResponse'] = _HASRESPONSE
DESCRIPTOR.message_types_by_name['ListResponse'] = _LISTRESPONSE
DESCRIPTOR.message_types_by_name['InfoResponse'] = _INFORESPONSE
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilterRequest = _reflection.GeneratedProtocolMessageType('FilterRequest', (_message.Message,), dict(
  DESCRIPTOR = _FILTERREQUEST,
  __module__ = 'bloom_pb2'
  # @@protoc_insertion_point(class_scope:pb.FilterRequest)
  ))
_sym_db.RegisterMessage(FilterRequest)

KeyRequest = _reflection.GeneratedProtocolMessageType('KeyRequest', (_message.Message,), dict(
  DESCRIPTOR = _KEYREQUEST,
  __module__ = 'bloom_pb2'
  # @@protoc_insertion_point(class_scope:pb.KeyRequest)
  ))
_sym_db.RegisterMessage(KeyRequest)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTREQUEST,
  __module__ = 'bloom_pb2'
  # @@protoc_insertion_point(class_scope:pb.ListRequest)
  ))
_sym_db.RegisterMessage(ListRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'bloom_pb2'
  # @@protoc_insertion_point(class_scope:pb.Response)
  ))
_sym_db.RegisterMessage(Response)

HasResponse = _reflection.GeneratedProtocolMessageType('HasResponse', (_message.Message,), dict(
  DESCRIPTOR = _HASRESPONSE,
  __module__ = 'bloom_pb2'
  # @@protoc_insertion_point(class_scope:pb.HasResponse)
  ))
_sym_db.RegisterMessage(HasResponse)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTRESPONSE,
  __module__ = 'bloom_pb2'
  # @@protoc_insertion_point(class_scope:pb.ListResponse)
  ))
_sym_db.RegisterMessage(ListResponse)

InfoResponse = _reflection.GeneratedProtocolMessageType('InfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _INFORESPONSE,
  __module__ = 'bloom_pb2'
  # @@protoc_insertion_point(class_scope:pb.InfoResponse)
  ))
_sym_db.RegisterMessage(InfoResponse)

Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), dict(
  DESCRIPTOR = _FILTER,
  __module__ = 'bloom_pb2'
  # @@protoc_insertion_point(class_scope:pb.Filter)
  ))
_sym_db.RegisterMessage(Filter)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\002pb'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class BloomStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.CreateFilter = channel.unary_unary(
          '/pb.Bloom/CreateFilter',
          request_serializer=FilterRequest.SerializeToString,
          response_deserializer=Response.FromString,
          )
      self.ListFilters = channel.unary_unary(
          '/pb.Bloom/ListFilters',
          request_serializer=ListRequest.SerializeToString,
          response_deserializer=ListResponse.FromString,
          )
      self.Info = channel.unary_unary(
          '/pb.Bloom/Info',
          request_serializer=ListRequest.SerializeToString,
          response_deserializer=InfoResponse.FromString,
          )
      self.Add = channel.unary_unary(
          '/pb.Bloom/Add',
          request_serializer=KeyRequest.SerializeToString,
          response_deserializer=Response.FromString,
          )
      self.Has = channel.unary_unary(
          '/pb.Bloom/Has',
          request_serializer=KeyRequest.SerializeToString,
          response_deserializer=HasResponse.FromString,
          )
      self.Clear = channel.unary_unary(
          '/pb.Bloom/Clear',
          request_serializer=FilterRequest.SerializeToString,
          response_deserializer=Response.FromString,
          )
      self.Drop = channel.unary_unary(
          '/pb.Bloom/Drop',
          request_serializer=FilterRequest.SerializeToString,
          response_deserializer=Response.FromString,
          )


  class BloomServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def CreateFilter(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ListFilters(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Has(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Drop(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_BloomServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateFilter': grpc.unary_unary_rpc_method_handler(
            servicer.CreateFilter,
            request_deserializer=FilterRequest.FromString,
            response_serializer=Response.SerializeToString,
        ),
        'ListFilters': grpc.unary_unary_rpc_method_handler(
            servicer.ListFilters,
            request_deserializer=ListRequest.FromString,
            response_serializer=ListResponse.SerializeToString,
        ),
        'Info': grpc.unary_unary_rpc_method_handler(
            servicer.Info,
            request_deserializer=ListRequest.FromString,
            response_serializer=InfoResponse.SerializeToString,
        ),
        'Add': grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=KeyRequest.FromString,
            response_serializer=Response.SerializeToString,
        ),
        'Has': grpc.unary_unary_rpc_method_handler(
            servicer.Has,
            request_deserializer=KeyRequest.FromString,
            response_serializer=HasResponse.SerializeToString,
        ),
        'Clear': grpc.unary_unary_rpc_method_handler(
            servicer.Clear,
            request_deserializer=FilterRequest.FromString,
            response_serializer=Response.SerializeToString,
        ),
        'Drop': grpc.unary_unary_rpc_method_handler(
            servicer.Drop,
            request_deserializer=FilterRequest.FromString,
            response_serializer=Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'pb.Bloom', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaBloomServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def CreateFilter(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ListFilters(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Info(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Add(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Has(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Clear(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Drop(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaBloomStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def CreateFilter(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    CreateFilter.future = None
    def ListFilters(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    ListFilters.future = None
    def Info(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Info.future = None
    def Add(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Add.future = None
    def Has(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Has.future = None
    def Clear(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Clear.future = None
    def Drop(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Drop.future = None


  def beta_create_Bloom_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('pb.Bloom', 'Add'): KeyRequest.FromString,
      ('pb.Bloom', 'Clear'): FilterRequest.FromString,
      ('pb.Bloom', 'CreateFilter'): FilterRequest.FromString,
      ('pb.Bloom', 'Drop'): FilterRequest.FromString,
      ('pb.Bloom', 'Has'): KeyRequest.FromString,
      ('pb.Bloom', 'Info'): ListRequest.FromString,
      ('pb.Bloom', 'ListFilters'): ListRequest.FromString,
    }
    response_serializers = {
      ('pb.Bloom', 'Add'): Response.SerializeToString,
      ('pb.Bloom', 'Clear'): Response.SerializeToString,
      ('pb.Bloom', 'CreateFilter'): Response.SerializeToString,
      ('pb.Bloom', 'Drop'): Response.SerializeToString,
      ('pb.Bloom', 'Has'): HasResponse.SerializeToString,
      ('pb.Bloom', 'Info'): InfoResponse.SerializeToString,
      ('pb.Bloom', 'ListFilters'): ListResponse.SerializeToString,
    }
    method_implementations = {
      ('pb.Bloom', 'Add'): face_utilities.unary_unary_inline(servicer.Add),
      ('pb.Bloom', 'Clear'): face_utilities.unary_unary_inline(servicer.Clear),
      ('pb.Bloom', 'CreateFilter'): face_utilities.unary_unary_inline(servicer.CreateFilter),
      ('pb.Bloom', 'Drop'): face_utilities.unary_unary_inline(servicer.Drop),
      ('pb.Bloom', 'Has'): face_utilities.unary_unary_inline(servicer.Has),
      ('pb.Bloom', 'Info'): face_utilities.unary_unary_inline(servicer.Info),
      ('pb.Bloom', 'ListFilters'): face_utilities.unary_unary_inline(servicer.ListFilters),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Bloom_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('pb.Bloom', 'Add'): KeyRequest.SerializeToString,
      ('pb.Bloom', 'Clear'): FilterRequest.SerializeToString,
      ('pb.Bloom', 'CreateFilter'): FilterRequest.SerializeToString,
      ('pb.Bloom', 'Drop'): FilterRequest.SerializeToString,
      ('pb.Bloom', 'Has'): KeyRequest.SerializeToString,
      ('pb.Bloom', 'Info'): ListRequest.SerializeToString,
      ('pb.Bloom', 'ListFilters'): ListRequest.SerializeToString,
    }
    response_deserializers = {
      ('pb.Bloom', 'Add'): Response.FromString,
      ('pb.Bloom', 'Clear'): Response.FromString,
      ('pb.Bloom', 'CreateFilter'): Response.FromString,
      ('pb.Bloom', 'Drop'): Response.FromString,
      ('pb.Bloom', 'Has'): HasResponse.FromString,
      ('pb.Bloom', 'Info'): InfoResponse.FromString,
      ('pb.Bloom', 'ListFilters'): ListResponse.FromString,
    }
    cardinalities = {
      'Add': cardinality.Cardinality.UNARY_UNARY,
      'Clear': cardinality.Cardinality.UNARY_UNARY,
      'CreateFilter': cardinality.Cardinality.UNARY_UNARY,
      'Drop': cardinality.Cardinality.UNARY_UNARY,
      'Has': cardinality.Cardinality.UNARY_UNARY,
      'Info': cardinality.Cardinality.UNARY_UNARY,
      'ListFilters': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'pb.Bloom', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
